services:
  movensys_manipulator:
    restart: unless-stopped
    build:
      context: .
      dockerfile: isaac-ros_3.2.Dockerfile
      network: host
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    privileged: true
    network_mode: host
    ipc: host
    runtime: nvidia
    working_dir: /home/admin/workspaces/movensys_ws
    entrypoint: ["/usr/local/bin/scripts/workspace-entrypoint.sh"]
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - HOST_USER_UID=${HOST_USER_UID}
      - HOST_USER_GID=${HOST_USER_GID}
      - USER=${USER}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
      - ISAAC_ROS_WS=/home/admin/workspaces/isaac_ros-dev
      - CYCLONEDDS_URI=file:///home/admin/workspaces/cyclonedds.xml
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
      - ISAAC_ROS_ACCEPT_EULA=1
      - ROS_DISTRO=${ROS_DISTRO}
      - MANIPULATOR_MODEL=${MANIPULATOR_MODEL}
      - ISAAC_MANIPULATOR_DIR=/home/admin/workspaces/movensys_isaac_manipulator
    volumes:
      - ${ISAAC_ROS_WS}:/home/admin/workspaces/isaac_ros-dev:rw
      - ${MOVENSYS_MANIPULATOR_PACKAGES}:/home/admin/workspaces/movensys_ws/src/movensys-manipulator:rw
      - ${ISAAC_MANIPULATOR_DIR}:/home/admin/workspaces/movensys_isaac_manipulator:ro
      - ${CYCLONEDDS_DIR}:/home/admin/workspaces/cyclonedds.xml:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri
    command: ["/bin/bash","-lc",
              "sudo chown -R admin:admin /home/admin/workspaces/movensys_ws && \
               source /opt/ros/humble/setup.bash && \

               echo ====== Link for numpy ======= && \
               sudo mkdir -p /usr/include && \
               sudo ln -sf /usr/local/lib/python3.10/dist-packages/numpy/core/include/numpy /usr/include/numpy && \

               echo ====== Preparation ======= && \
               sudo apt-get update && \

               echo ====== Isaac ROS Setup ======= && \
               ISAAC_WS=/home/admin/workspaces/isaac_ros-dev && \
               ISAAC_SRC=$ISAAC_WS/src && \
               mkdir -p $ISAAC_SRC && \

               cd $ISAAC_SRC && \
               [ -d isaac_ros_common ]      || git clone -b release-3.2 https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common.git isaac_ros_common && \
               [ -d isaac_manipulator ]     || git clone --recursive -b release-3.2 https://github.com/NVIDIA-ISAAC-ROS/isaac_manipulator.git isaac_manipulator && \
               [ -d isaac_ros_nvblox ]      || git clone --recursive -b release-3.2 https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox.git isaac_ros_nvblox && \
               [ -d ros2_robotiq_gripper ]  || git clone --recursive https://github.com/NVIDIA-ISAAC-ROS/ros2_robotiq_gripper && \
               [ -d serial ]               || git clone -b ros2 https://github.com/tylerjw/serial && \

               echo ====== Configure RealSense ======= && \
               touch $ISAAC_SRC/isaac_ros_common/scripts/.isaac_ros_common-config && \
               echo CONFIG_IMAGE_KEY=ros2_humble.realsense > $ISAAC_SRC/isaac_ros_common/scripts/.isaac_ros_common-config && \

               echo ====== Patch isaac_manipulator_pick_and_place ======= && \
               PICK_AND_PLACE=$ISAAC_SRC/isaac_manipulator/isaac_manipulator_pick_and_place && \
               REVISE_DIR=/home/admin/workspaces/movensys_isaac_manipulator/revise_isaac_manipulator_pick_and_place && \
               sudo rm -rf $PICK_AND_PLACE/CMakeLists.txt $PICK_AND_PLACE/launch/isaac_sim_workflows.launch.py && \
               sudo cp $REVISE_DIR/CMakeLists.txt $PICK_AND_PLACE/CMakeLists.txt && \
               sudo cp $REVISE_DIR/isaac_sim_workflows.launch.py $PICK_AND_PLACE/launch/isaac_sim_workflows.launch.py && \
               sudo cp $REVISE_DIR/camera_info_publisher.py $PICK_AND_PLACE/scripts/camera_info_publisher.py && \
               sudo chmod +x $PICK_AND_PLACE/scripts/camera_info_publisher.py && \

               echo ====== Build ROS control pkgs ======= && \
               cd $ISAAC_WS && \
               rosdep update && \
               rosdep install -i -r \
                  --from-paths $ISAAC_SRC/isaac_manipulator/isaac_manipulator_bringup/ \
                  --from-paths $ISAAC_SRC/isaac_ros_nvblox/ \
                  --rosdistro humble -y && \
               colcon build --symlink-install \
                  --packages-select-regex robotiq.* serial --cmake-args '-DBUILD_TESTING=OFF' && \
               source install/setup.bash && \
               colcon build --symlink-install \
                  --packages-select isaac_manipulator_bringup isaac_manipulator_pick_and_place \
                                    isaac_manipulator_interfaces isaac_manipulator_servers isaac_ros_nvblox && \
               source install/setup.bash && \

               echo ====== Build movensys_manipulator ======= && \
               cd /home/admin/workspaces/movensys_ws && \
               source /opt/ros/humble/setup.bash && \
               colcon build --symlink-install && \

               echo ====== Pytorch compatibility on Blackwell GPU ======= && \
               sudo mkdir -p /home/admin/.cache/torch_extensions && \
               sudo rm -rf /home/admin/.cache/torch_extensions/py310_cu128 && \
               sudo chown -R $(id -u):$(id -g) /home/admin/.cache/torch_extensions && \
               sudo mkdir -p /home/admin/.cache/warp && \
               sudo chown -R $(id -u):$(id -g) /home/admin/.cache/warp && \

               echo ====== Build Terminated ======= && \
               source /home/admin/workspaces/movensys_ws/install/setup.bash && \
               export RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION} && \
               exec bash"
              ]
