isaacsim_bridge:
  ros__parameters:
    joint_names:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    joint_command_topic: /joint_command
    joint_states_topic:  /joint_states
    action_name: /movensys_manipulator_arm_controller/follow_joint_trajectory
